name = "enco-auth-api"
main = "worker.js"
compatibility_date = "2024-09-23"

# Binding ke Cloudflare D1 Database
[[d1_databases]]
binding = "DB"
database_name = "enco_db"
database_id = "MASUKKAN_DATABASE_ID_D1_DISINI"

# Deployment assets (hosting web portal pendaftaran & control panel)
[assets]
directory = "./public"
binding = "ASSETS"
